src/webhttp/blueprint.py
from flask import render_template, Blueprint, redirect, url_for, request
from src.service.logic.user_logic import user_details
from src.service.logic.dictionary_logic import DictionaryLogic, WordListFilter
import re
from flask_login import login_required
from src.service.util.logger import *
import jinja2

home_blueprint = Blueprint('home', __name__)
content_blueprint = Blueprint('content', __name__)
"""
admin_blueprint = Blueprint(
    'admin',
    __name__,
    template_folder='templates/admin',
    url_prefix=""
)
"""


@home_blueprint.route('/home')
def home(page=1):
    return render_template('templates/content/base.html')


@home_blueprint.route('/user/<string:post_id>')
def user(post_id):
    print('user1')
    user_detail, post = user_details(post_id)
    if not user_detail:
        print(user_detail.username)

    return render_template(
        'templates/content/user.html',
        user=user_detail,
        posts=post,
        recent={},
        top_tags={}
    )


@home_blueprint.route('/admin')
@login_required
def admin(page=1):
    return redirect('http://127.0.0.1:1058/admin/')


# Content Blue Print
@content_blueprint.route('/')
def home(page=1):
    user_detail, post = user_details(page)
    print(user_details)
    return render_template(
        'templates/content/home.html',
        posts={},
        recent={},
        top_tags={}
    )


@content_blueprint.route('/<int:page>')
def article(page=1):
    return render_template('templates/content/base.html')


# /content/deutsch/list?srch=b
@content_blueprint.route('/deutsch/list')
@content_blueprint.route('/deutsch/list&channel=<channel>')
def deutsch(channel=None):
    _word_filter = None

    rule = re.split('\?srch=', request.full_path, 1)
    if len(rule) > 1:
        channel = rule[1]
        print(channel)

    if channel is not None:
        _filters = {'letter': channel, 'sape': 4139, 'page_size': 100}
        _word_filter = WordListFilter()
        _word_filter.parse(_filters)

    _logic = DictionaryLogic()
    try:
        _word_list, _page = _logic.get_list(_word_filter)
    except Exception as ex:
        log_traceback(ex)
        _word_list = []

    return render_template(
        'templates/content/deutsch.html',
        words=_word_list,
        recent={},
        top_tags={}
    )


"""
# Admin Blue Print
@admin_blueprint.route('/')
def home(page=1):
    return "Hello Joe"


@admin_blueprint.route('/<int:page>')
def admin(page=1):
    return render_template('content/base.html')
"""


# Public Register def
def register_blueprint(app):
    @app.route('/react')
    def test():
        return render_template('react/index.html')

    # @app.route('/')
    # def index():
    #   return render_template('index.html')
        # url = url_for('content.deutsch')  # content_blueprint - home(def)
        # print(url)
        # return redirect(url)

    app.register_blueprint(home_blueprint, url_prefix='')
    app.register_blueprint(content_blueprint, url_prefix='/content')
    # app.register_blueprint(admin_blueprint, url_prefix='/admin')

    register_add_url_rule(app)
    register_error_handlers(app)
    register_templates_and_static(app)


def register_error_handlers(app):
    def render_error(error):
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code

    for errcode in [500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_add_url_rule(app):
    @app.route("/hello/<username>")
    def hello_user(username):
        return 'Hello: %s' % username

    @app.route('/post/<int:post_id>', methods=('GET', 'POST'))
    def post(post_id):
        return {"": "gfdgdfg"}


def register_templates_and_static(app):
    _template_path = jinja2.ChoiceLoader([
        app.jinja_loader,
        jinja2.FileSystemLoader('www'),
    ])
    app.jinja_loader = _template_path

www/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}J.com{% endblock %}</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="For SEO.">
    <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    <script>
        document.write("<base href='http://" + document.location.host + "' />");
    </script>
    <link rel="shortcut icon" href="static/img/favi.ico"/>
    <link rel="stylesheet" href="static/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/styles.css">
    <style>
        .small-card2 {
            max-width: 500px;
            margin-left: auto;
            margin-right: auto;
            min-height: 250px;
        }
    </style>

</head>
<body>
{% include "templates/header.html" %}

{% block base_body_fill %}
{% endblock %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

www/templates/header.html
<nav class="navbar navbar-fixed-top header"> 

    <div class="col-md-12"> 
        <div class="navbar-header">   <a href="{{ url_for('content.deutsch') }}" class="navbar-brand"
                                         style="color:#ff7277;">Joe.com</a> 
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse1">  <i
                    class="glyphicon glyphicon-list" style="color:#ff7277;"></i> 
            </button>
              
        </div>
         
        <div class="collapse navbar-collapse" id="navbar-collapse1"> 

            <form class="navbar-form pull-left"> 

                <div class="input-group" style="max-width:470px;"> 
                    <input type="text" class="form-control" placeholder="Search" name="srch" id="srch-term"> 
                    <div class="input-group-btn"> 
                        <button class="btn btn-default btn-primary" type="submit" style="background-color:#ff7277;"><i 
                            class="glyphicon glyphicon-search"></i>
                        </button>
                         
                    </div>
                     
                </div>
                 
            </form>
             
            <ul class="nav navbar-nav navbar-right"> 
                <li>  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i
                        class="glyphicon glyphicon-bell"></i></a> 
                    <ul class="dropdown-menu"> 
                        <li><a href="#"><span class="badge pull-right">40</span>Link</a></li>
                         
                        <li><a href="#"><span class="badge pull-right">2</span>Link</a></li>
                         
                        <li><a href="#"><span class="badge pull-right">0</span>Link</a></li>
                         
                        <li><a href="#"><span class="label label-info pull-right">1</span>Link</a></li>
                         
                        <li><a href="#"><span class="badge pull-right">13</span>Link</a></li>
                         
                    </ul>
                     
                </li>
                 
                <li>  <a href="{{ url_for('home.admin') }}" id="btnAdmin"><i
                        class="glyphicon glyphicon-th-large"></i></a> 
                </li>
                 
                <li>  <a href="#" id="btnAccount" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="glyphicon glyphicon-user"></i></a> 
                    <ul class="nav dropdown-menu"> 
                        <li><a href="#"><i class="glyphicon glyphicon-user" style="color:#1111dd;"></i> Profile</a></li>
                         
                        <li><a href="#"><i class="glyphicon glyphicon-tags" style="color:#0000aa;"></i>
                            Help</a></li>
                         
                        <li><a href="#"><i class="glyphicon glyphicon-cog" style="color:#11dd11;"></i> Settings</a></li>
                         
                        <li class="nav-divider"></li>
                         
                        <li><a href="{{ url_for('logout') }}"><i class="glyphicon glyphicon-log-out"></i> Log Out</a>
                        </li>
                         
                        <li><a href="#"><i class="glyphicon glyphicon-plus"></i> More..</a></li>
                         
                    </ul>
                </li>
                 
            </ul>
             
        </div>

         
    </div>

     

</nav>

www/templates/index.html
{% block title %}Home{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-lg-9">
            {% for post in posts.items %}
                <div class="row">
                    <div class="col-lg-12"><h1>{{ post.title }}</h1></div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        {{ post.text | truncate(500) | safe }} 
                        <a href="{{ url_for('.post', post_id=post.id) }}">Read More</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-lg-3">
            <div class="row">
                <h5>Recent Posts</h5>
                <ul>
                    {% for post in recent %}
                        <li><a href="{{ url_for('.post', post_id=post.id) }}">{{ post.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="row">
                <h5>Popular Tags</h5>
                <ul>
                    {% for tag in top_tags %}
                        <li><a href="{{ url_for('.tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    {{ render_pagination(posts, '.home') }}
{% endblock %}